KC3Kai/kc3-translations

data/id/quests.json

Update,B22 we can use 1 CL as flagship, after i try looking again on wiki and try it, and it works.
i just update it for english and indonesia,
i hope other translator change that quest too,

Update quest B22

---

data/en/quests.json

Shorten the quest C7 to solve the popup overflow.

C7 Shortening

---

data/en/items.json

Long overdue update for equip names

Equipment update

---

data/en/ships.json
data/en/terms.json
data/id/terms.json
data/troll/terms.json

i don't really recall much about "-A" suffix issue, although it doesn't give much change to the `mstship` one...
(for lodger terms, some of them still not-in-so-serious one, feel free to recorrect this one, ~~~gonna put some lolz on indonesian later on along with salty bombs~~~)

"-A" Suffix and Lodger Terms

---

data/en/terms.json
data/scn/terms.json

See: https://github.com/KC3Kai/KC3Kai/pull/1136

Option for forcing English ship type

---

data/en/terms.json
data/scn/terms.json

See: https://github.com/KC3Kai/KC3Kai/pull/1135

terms for server maintenance

---

data/en/quests.json

Requested and done by mikenzb on behalf on his/her friend.
Also changed all the tabs into spaces.

[ENG] Added wiki quest numbers

---

data/en/quests.json

in quests bd5 and bw4
it's been bugging me for months

changed "bosses in horned nodes" to "boss nodes"

---

data/en/terms.json

see https://github.com/KC3Kai/KC3Kai/pull/1441
Might not be the best choice in case of sense, but better then nothing :)

added text for new setting

---

data/fr/equiptype.json

This time everything should be okay, sorry again :/.
I'm understanding better how GitHub is working so I shouldn't make these errors again.

Corrected some things because the travis test failed

---

data/en/terms.json

Added notice for API Gameplay for whitescreen fix

[EN] API Gameplay Flash Notice

---

data/en/quests.json

Not going to merge this right away. Will do it before the Kinu Kai Ni patch if there are no objections.
Large-scale cleanup with changes for noob-friendliness and QoL.
I'll go into more detail on what this is later.
I'm open to criticisms as always.
It's a job I've worked on for 2 weeks, taking as much care to not introduce errors as I could.

[EN] quests.json translation overhaul

---

data/en/terms.json
data/scn/terms.json

See details here: https://github.com/KC3Kai/KC3Kai/pull/1687
@KC3Kai/translators new terms for translation:
- ExpedBaseNormal
- ExpedBaseGreat
- ExpedAveStars
- ExpedBonus
- ExpedBonusToku
- ExpedResupply
- ExpedTotalIncome
examples are provided in this PR for English and Simplified Chinese.

new terms for expedition tab

---

data/en/terms.json
data/scn/terms.json

See: https://github.com/KC3Kai/KC3Kai/pull/1724
@KC3Kai/translators new terms for translation:
- ExpedGSRate
- ExpedGSRateExplainSparkle
- ExpedGSRateExplainExtraDrum
you can tick on your language when done:

New terms for expedition panel

---

data/en/terms.json

* UpdateAvailableNow
* SettingsUpdateNotification
* SettingsUpdateNotifNone
* SettingsUpdateNotifPage
* SettingsUpdateNotifPop
* InstalledText
* UpdatedText
* UpdateNotifTitle
* UpdateNotifText
* PageUpdateTitle
* PageUpdateReady
* PageUpdateReadyText
* PageUpdateRestartNow
* PageUpdateRestartLater
* PageUpdateHowToManual
* InstalledTitle
* InstallText
* UpdateText

[EN] Feature: Officially handle updating the extension

---

data/en/terms.json
data/scn/terms.json

See: https://github.com/KC3Kai/KC3Kai/pull/1802

new term for translation

---

data/en/quests.json

First time doing something in the TL repo, added in 6 new EN quests from 2/28 update, would like some validation on the quests, I have validated the quest IDs are correct on my end but haven't done all the quests yet.
TL Source: [EN Kancollewiki](http://en.kancollewiki.net/wiki/Quests#February_28th.2C_2017)

[EN] WIP quests for 2/28

---

data/id/equiptype.json
data/id/items.json
data/id/quotes.json
data/id/ship_affix.json
data/id/ships.json

i.. err.. 
i don't know what to say.. xD

[ID] Updates

---

data/en/items.json
data/en/quests.json

Just some small changes here and there.

[EN] Minor TL updates

---

data/en/terms.json
data/ru/terms.json

Related to https://github.com/KC3Kai/KC3Kai/pull/1959

Add translations for Quests Synchronization

---

data/en/terms.json

Needed by https://github.com/KC3Kai/KC3Kai/pull/1966

Add terms for GS rate

---

data/en/terms.json
data/ru/terms.json

* Simplify quests synchronization notification
* Add translation for enabling data synchronization notification
Related to https://github.com/KC3Kai/KC3Kai/pull/1965

[EN], [RU] Update translations for data synchronization

---

data/en/quotes.json

Added and enabled Spring seasonals.
Also fixed Abukuma's MVP and Zuihou's Sortie.

[EN] Spring quotes + minor fixes

---

data/scn/terms_extend.json

@Javran @Diablohu 
这是新增的作战指挥所的翻译，麻烦大佬帮忙看下翻译是否合适，terms_extend.json 除了新增的内容外还从terms.json移过来了一些已有内容比如NewsfeedRepair，我没做更改直接拿来了

[scn] translation for strategy room

---

data/en/quests.json

Sources: 
http://wikiwiki.jp/kancolle/?%C7%A4%CC%B3
http://kancolle.wikia.com/wiki/Quests#B45
http://en.kancollewiki.net/wiki/Quest#B45

[EN] Mistake of requirement in B45

---

data/en/terms.json

Required by https://github.com/KC3Kai/KC3Kai/pull/2079
(Do not merge until the aforementioned PR is ready.)

Add EN translation for Log settings

---

data/en/quests.json

[EN] quest minor fix

---

data/en/battle.json

Needed for https://github.com/KC3Kai/KC3Kai/pull/2357

Add ASW support expedition

---

data/id/quests.json

didn't see the error without travis-kun :/

[ID] Quest test Update

---

data/de/quests.json

[DE] Minor Fixes and Changes

---

data/de/quests.json

*Translations for the new Quests

[DE] Added the new Quests

---

data/de/battle.json
data/de/quests.json

*Updated/Fixed the Memo and Description for Quest C16
*Updated AACI Tip

[DE] Update/Fix for Quest C16's Memo/Desc, AACI Update

---

data/fr/battle.json

Translate the english battle.json to french

fr translate battle.json

---

data/en/terms.json

https://github.com/KC3Kai/KC3Kai/pull/2971

Quest activity

---

data/troll/terms.json

Shorten overly long line
Add 1 more line

[Troll] adjustment

---

data/troll/terms.json

Extra line for lack of LBAS air raid defense

[Troll] extra line

---

data/en/terms.json
data/jp/terms.json
data/scn/terms.json
data/tcn-yue/terms.json
data/tcn/terms.json
data/tctn/terms.json

https://github.com/KC3Kai/KC3Kai/pull/3241#pullrequestreview-1078979027

[EN+JP+CN] Add ExpeditionOnly term

---

data/tcn/terms.json

Misunderstood what it is used for... fixed.

[TCN] Modernization results tip

---

data/en/quests.json

Added missing quests starting from the 2024-09-24 update

[EN] Add quests
